### ISSUE TITLE
Add Crowdstrike

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/docker-community-extensions#102]
CrowdStrike is a cybersecurity company that provides endpoint protection, threat intelligence, and incident response services. Its flagship product, the CrowdStrike Falcon platform, uses artificial intelligence and machine learning to detect and prevent cyber threats in real-time. The platform also provides detailed insights into attacker behavior and post-attack forensics to help organizations understand and respond to security incidents.
@sivolko 

https://github.com/CrowdStrike/crowdstrike-container-extension/

**Comment by sivolko** [comment]
On it

**Comment by sivolko** [comment]
Raised PR for the same

**Comment by collabnix** [comment]
Added.
