### ISSUE TITLE
Add Deploy to the Extension List under API Testing

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/docker-community-extensions#162]
Keploy Docker Extension is a developer-centric API testing tool that creates backend tests along with built-in mocks, faster than unit tests.

Keployio  is an AI-based test case and stubs/mocks generator for e2e testing. 90% test coverage in minutes with open source testing tool

https://github.com/Yaxhveer/keploy-docker-extension

**Comment by ajeetraina** [comment]
Cc @sivolko

**Comment by sivolko** [comment]
Added, Feel free to close issue #162
