### ISSUE TITLE
Restore microcks-docker-desktop-extension

### ISSUE THREAD

**Issue by lbroudoux** [collabnix/docker-community-extensions#79]
Hi there,

Thanks for your work on this awesome extensions list! 

We saw that the [Microcks Docker Desktop Extension](https://microcks.io/documentation/installing/docker-desktop-extension/) that was on the list has been removed a few days ago from the **API** section (see [commit](https://github.com/collabnix/docker-community-extensions/commit/d49c0b53f7a47733b0397cb0cd7728c0251a3fd4)) 😢 

Have you faced some issues with this extension? Or do you need more information on it? Is it possible to restore it?

Thanks a lot,

**Comment by collabnix** [comment]
@lbroudoux Thanks for your feedback.

We haven't removed the Microcks Docker Desktop from the list. We just structured the list and moved it to the list of Extension Marketplace under https://github.com/collabnix/docker-community-extensions#list-of-docker-marketplace-extensions.

Said that we are always open to your feedback and ideas for improving this extension list.

**Comment by ajeetraina** [comment]
Hi, @lbroudoux I have added a separate section called "List of Marketplace" to keep it simple.
This time I have put them into a tabular format. Hope it looks good.

Also, I moved "Table of Contents" down so that you don't skip the marketplace entries.

**Comment by lbroudoux** [comment]
Awesome. Thanks a lot!
